name: test_env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - cubedsphere
  - xarray
  - numpy
  - pytest
  - future
  - zarr
  - cftime
  - aiohttp
  - pytest-cov
  - codecov
  - fsspec
  - cachetools
  - pip
  - pip:
      - git+https://github.com/MITgcm/xmitgcm.git
      - git+https://github.com/pydata/xarray.git
